### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by chaidhat** [Chai112/Chai112-s-Boeing-777-300ER#3]
**Information**
Client: David Prosche
Contact date: 01/12/2019
Reference Ticket: https://forums.x-plane.org/index.php?/messenger/556085/

**Describe the problem**
I downloaded your 777 for XP11 but when I loaded XP it just quits when I try to load the aircraft and I've tried several times but couldn't get it to work.

 I recently downloaded your 777-300ER v0.42.0 ED and I currently use XP11.41 and when I loaded the plane, XP suddenly quits. But when I put your plane as an AI aircraft when I'm flying a different aircraft, your plane shows up as AI.

Same said for v0.41.1 which says it works for XP11, (It doesn't work at all).

**To Reproduce**
1. Load aircraft

**Screenshots**
None.

**Crash Log**
[Log.txt](https://github.com/Chai112/Chai112-s-Boeing-777-300ER/files/4267007/Log.txt)

**Comment by bennetsong08** [comment]
yea same with me, delete SASLFree/64/mac.xpl to fix it,

**Comment by chaidhat** [comment]
> yea same with me, delete SASLFree/64/mac.xpl to fix it,

The majority of the simulation code is in there so deleting it would remove at least 40 hours of work. I'll try updating SASL to XP11 before any deleting it. Thank you for your suggestion :)

**Comment by chaidhat** [comment]
Good thing to note that the problem occurs on maxosx

**Comment by bennetsong08** [comment]
any updates?

**Comment by bennetsong08** [comment]
i look forward to flying this. also it seems that someone on the org called "777fan123" also has that issue.

**Comment by chaidhat** [comment]
pushed a new commit (v0.42.1) which should resolve the issue. Please give feedback whether or not it has

**Comment by bennetsong08** [comment]
ok, i'll try it over the weekend. i have a ultra-busy schedule. thanks. 
PS great work one the a320 cockpit i just downloaded it a few days ago, it is AWESOME!

**Comment by bennetsong08** [comment]
i think it works now on mac, tried it 2 times and it works. hopefully the problem doesnt reoccur!

**Comment by chaidhat** [comment]
fantastic :) Thank you very much for your help and testing
