### ISSUE TITLE
Gear fix

### ISSUE THREAD

**Issue by filipporomani** [Chai112/Chai112-s-Boeing-777-300ER#30]
**Information**
Client: filipporomani
Contact date: 2
Reference Ticket: Contact you here

**Describe the problem**
When i retract the gear, the right and the nose one are stuck down. The right one is white and seems to be kinda "broken", both won't go up.

**To Reproduce**
1. Download latest version
2. Start a flight with the 777
3. Takeoff and try to retract the gear

**Screenshots**
![image](https://user-images.githubusercontent.com/72656809/119506004-c9d20000-bd6d-11eb-9bcd-dace7062cdc1.png)

Also lights are in the wrong position.

**Comment by chaidhat** [comment]
Hello,

Thank you very much for submitting this an issue, I believe these issues have been logged already in the prior reports so I've just added a duplicate label. This has already been fixed for v1.0, however it is still private. Thank you for your patience.

Chai

**Comment by filipporomani** [comment]
Thank you so much, I'm waiting for the v1.0!!

**Comment by filipporomani** [comment]
Sorry, just to ask, when do you plan to release V1?

**Comment by chaidhat** [comment]
Hi, sorry it's delayed because of life, studies and SATs. So to answer your question, I don't know I'm afraid.
